name: 'Trigger update of CV and srvanderplas.github.io'

on:
  push:
    branches: main
      
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo workflow name
        shell: bash
        run: |
          echo "I am workflow of cv-data"
      - name: Trigger CV repo build
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: srvanderplas
          repo: CV
          github_token: ${{ secrets.GH_TOKEN }}
          workflow_file_name: publish.yml
          ref: master
          wait_interval: 100
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: false
      - name: Trigger site repo build
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: srvanderplas
          repo: srvanderplas.github.io
          github_token: ${{ secrets.GH_TOKEN }}
          workflow_file_name: publish.yml
          ref: main
          wait_interval: 100
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: false
